### PR TITLE
feat: Watchlist backend fully implemented and connected routes

### PR DESCRIPTION
**Pull request by hopieyimmie**
For some reason, the NavBar didn't include the 'My Watchlist' at the top. I added that in the file so only users that are logged in can see their own watchlist. 
The watchlist is fully functional with the frontend and backend connecting. Once the movie is added to the watchlist, it links to the Single Movie Page with all of the details (Issue #49 will be done later once this is approved and merged). The frontend part of the watchlist page is similar to the landing page's layout on the movies, but let me know if there is anything else I can do to change or fix things!

### CODE REVIEW

**Review by nickambrose7 — APPROVED** [review]
Everything looks great!

**Review by hsterry — CHANGES_REQUESTED** [review]
It looks like when you add a movie to the watch list it gets saved into multiple accounts. I would consider taking a look at this before we merge to main.

**Review by NickAspiras — APPROVED** [review]
I agree with Hailey. Once the watchlist saves to a single user, it looks good to merge! Great work on this

**Comment by hopieyimmie** [comment]
Thank you for the feedback everyone! I will let you all know when the PR is ready to be reviewed again!

**Comment by hopieyimmie** [comment]
Just committed and got the movies to be added to user's own watchlist! Please review and sooner the approval, the faster I can get the removing movies from watchlist and help with whatever!

**Review by hsterry — COMMENTED** [review]
It looks like you may have committed the node modules folder, I could be wrong here but we may want to double check that's not getting into main -- other than that the changes look great!

**Review by NickAspiras — APPROVED** [review]
LGTM!

**Review by hsterry — APPROVED** [review]

**Review by nickambrose7 — APPROVED** [review]
Changes look great!

**Pull request merged**
