### PR TITLE
Hailey dev

### PR DESCRIPTION
**Pull request by hsterry**
Adding unit test files that have 100% coverage for the models. Additional stylistic changes on the landing page.

### CODE REVIEW

**Review by nickambrose7 — APPROVED** [review]
LGTM!!!

**Review by nickambrose7 — APPROVED** [review]
Great! The styling looks fantastic!

**Review by hopieyimmie — APPROVED** [review]
Looks great to me! I think we should talk about how we should organize our code (curly braces, parentheses, spaces, etc) so we can keep things unified.

**Comment by hsterry** [comment]
> Looks great to me! I think we should talk about how we should organize our code (curly braces, parentheses, spaces, etc) so we can keep things unified.

I will review our style guide and update in the next pr!

**Review by NickAspiras — APPROVED** [review]
Looks great hailey! Great work on getting the test suite / CICD up to date!

**Comment by hsterry** [comment]
> > Looks great to me! I think we should talk about how we should organize our code (curly braces, parentheses, spaces, etc) so we can keep things unified.
> 
> I will review our style guide and update in the next pr!

The styling has been updated!

**Pull request merged**
